version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
